# Based on a pytorch image where cuda and cudnn are already installed.
# Newer version of this image would not work due to the nividia driver version on DGX1.
FROM nvcr.io/nvidia/pytorch:20.08-py3

# Install tmux
RUN apt-get update && apt-get install -y tmux htop