model_name: sentence-transformers/sentence-t5-large
weight_decay: 0.01
learning_rate: 1.0e-05
lr_scheduler_max_steps: null
lr_scheduler_type: null
lr_scheduler_num_warmup_steps: null
distance_func: cosine
loss_type: cross-entropy
margin: null
hidden_states_type: encoder-last
data_source_yaml_path: datasets/product_title_embedding/wish-aliexpress.yaml
raw_cache_dir: /data/junwang/.cache/general
batch_size: 32
overwrite_cache: false
max_length: 50
predict_on_test: true
num_workers: 80
max_length_out: 50
