policy:
  approval:
    - or:
      - FORCE_COMMIT
      - auto_approve
      - auto_approve_person
      - or:
        - ke_data_review
        - ke_data_person_review

approval_rules:
  # rule to allow for forcible commits regardless of regular review process
  # this should be only used in the event of a site-outage and oncall is responding.
  - name: FORCE_COMMIT
    requires:
      count: 1
      # only some users are allowed to give this sort of commit
      teams: ["ContextLogic/org_ke_data_ft"]
    options:
      allow_author: true
      allow_contributor: true
      methods:
        comments:
          - FORCE_COMMIT

  # If status checks indicate that change can be auto approved, change doesn't need human review
  - name: auto_approve
    if:
      has_successful_status:
        - "auto-approve"
    requires:
      count: 0
    options:
      invalidate_on_push: true
  
  - name: auto_approve_person
    if :
      has_author_in:
        users: ["junwang-wish"]
    requires:
      count: 0
    options:
      invalidate_on_push: true

  - name: ke_data_review
    if:
      changed_files:
        paths:
          - "./*"
    requires:
      count: 1
      teams: ["ContextLogic/org_ke_data_ft"]
    options:
      invalidate_on_push: true
      methods:
        github_review: true
  
  - name: ke_data_person_review
    if:
      changed_files:
        paths:
          - "./*"
    requires:
      count: 1
      users:
      - junwang-wish
    options:
      allow_author: true
      invalidate_on_push: true
      methods:
        github_review: true
