# pytorch_lightning==1.7.7
seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: models
      name: demo
      version: 4
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      agg_key_funcs: null
      agg_default_func: null
      comment: ''
      purge_step: null
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''
  enable_checkpointing: true
  callbacks:
  - init_args:
      dirpath: models/demo/version_4
      filename: null
      monitor: val_loss
      verbose: false
      save_last: null
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
    class_path: pytorch_lightning.callbacks.ModelCheckpoint
  - init_args:
      logging_interval: step
      log_momentum: false
    class_path: pytorch_lightning.callbacks.LearningRateMonitor
  default_root_dir: models/demo
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: auto
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: -1
  min_epochs: null
  max_steps: 200
  min_steps: null
  max_time: null
  limit_train_batches: 1000
  limit_val_batches: 50
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: cpu
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
model:
  model_name: t5-base
  weight_decay: 0.1
  learning_rate: 0.0001
  lr_scheduler_max_steps: null
  lr_scheduler_type: null
  lr_scheduler_num_warmup_steps: null
  distance_func: cosine
  loss_type: cross-entropy
  margin: null
  hidden_states_type: encoder-last
  add_simcse: true 
  label_map_file: datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
  label_weight_type: ancestor-high
  multitask_names:
  - clm
  - dlm
  - emb
  - seqclf
  auto_task_weight: true
data:
  model_name: t5-base
  multitask_dict:
    clm:
      data_source_yaml_path: datasets/demo/demo_conditional_lm.yaml
      batch_size: 16
      max_length: 50
      max_length_out: 50
    dlm:
      data_source_yaml_path: datasets/demo/demo_denoise_lm.yaml
      batch_size: 16
      max_length: 50
      max_length_out: 50
      mask_prob: 0.3
      use_ul2: true
    emb:
      data_source_yaml_path: datasets/demo/demo_embedding.yaml
      batch_size: 16
      max_length: 50
      max_length_out: 50
    seqclf:
      data_source_yaml_path: datasets/demo/demo_seqclassify.yaml
      batch_size: 16
      max_length: 50
      label_map_file: datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
  raw_cache_dir: /data/junwang/.cache/general
  overwrite_cache: false
  predict_on_test: true
  num_workers: 80
  multiple_trainloader_mode: max_size_cycle
ckpt_path: null
