model_name: hkunlp/instructor-base
weight_decay: 0.1
learning_rate: 1.0e-05
lr_scheduler_max_steps: null
lr_scheduler_type: null
lr_scheduler_num_warmup_steps: null
distance_func: cosine
loss_type: cross-entropy
margin: null
hidden_states_type: encoder-mean
add_simcse: false
manual_loss_type: manual_mse
auto_task_weight: false
multitask_specs_dict:
  emb_singlemodal_wishquery2googletitle: null
  seqclf_singlemodal_wishtitle2v121tax:
    specs:
      clf_head: clf_head_product
      clf_weight_type: null
      label_map_file: /workspaces/multitask-llm-rnd/modelling/datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
      label_type: multilabel_taxonomy
  seqclf_singlemodal_wishquery2v121tax:
    specs:
      clf_head: clf_head_query
      clf_weight_type: null
      label_map_file: /workspaces/multitask-llm-rnd/modelling/datasets/taxonomy/wish_v1.2.1_newtax_allpaths_withunknown.txt
      label_type: multilabel_taxonomy
head_dict:
  clf_head_product:
    purpose: seqclf
    type: linear
    in_features: 768
    out_features: 6037
  clf_head_query:
    purpose: seqclf
    type: linear
    in_features: 768
    out_features: 6038
return_model: true
cache_dir: null
force_download: false
resume_download: false
proxies: null
use_auth_token: null
local_files_only: false
revision: null
trust_remote_code: null
subfolder: ''
load_weights_only: true
multitask_dict:
  emb_singlemodal_wishquery2googletitle:
    data_source_yaml_path: datasets/multimodal_multitask/wish_query_all_googlescrape.yaml
    batch_size: 100
    max_length: 50
    max_length_out: 50
    llm_type: emb
    input_dict:
      template: '{title}'
      task_prefix: 'Represent the E-commerce product title for retrieval: '
    output_dict:
      template: '{query}'
      task_prefix: 'Represent the E-commerce search query for retrieval: '
    transform_dict: null
    data_source_type: dvc
  seqclf_singlemodal_wishtitle2v121tax:
    data_source_yaml_path: datasets/multimodal_multitask/liang_product_mixall_withoffshorev2valtest_multilabel_seqclf.yaml
    batch_size: 10
    max_length: 50
    max_length_out: 50
    label_map_file: /workspaces/multitask-llm-rnd/modelling/datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
    label_type: taxonomy
    llm_type: seqclf
    input_dict:
      template: '{title}'
      task_prefix: 'Represent the E-commerce product title for classification: '
    output_dict:
      template: '{category_path}'
    transform_dict:
      category_path: taxonomy
    data_source_type: dvc
  seqclf_singlemodal_wishquery2v121tax:
    data_source_yaml_path: datasets/multimodal_multitask/wish_labelled_inferred_modelpseudo_deduppathoverlap_multilabel_seqclf.yaml
    batch_size: 10
    max_length: 50
    max_length_out: 50
    label_map_file: /workspaces/multitask-llm-rnd/modelling/datasets/taxonomy/wish_v1.2.1_newtax_allpaths_withunknown.txt
    label_type: multilabel_taxonomy
    llm_type: seqclf
    input_dict:
      template: '{query}'
      task_prefix: 'Represent the E-commerce search query for classification: '
    output_dict:
      template: '{category}'
    transform_dict: null
    data_source_type: dvc
raw_cache_dir: /data/junwang/.cache/general
overwrite_cache: false
force_download_hfdata: false
predict_on_test: true
predict_on_trainval: null
num_workers: 0
multiple_trainloader_mode: min_size
