model_name: t5-base
weight_decay: 0.01
learning_rate: 1.0e-05
lr_scheduler_max_steps: null
lr_scheduler_type: null
lr_scheduler_num_warmup_steps: null
return_model: true
cache_dir: null
force_download: false
resume_download: false
proxies: null
use_auth_token: null
local_files_only: false
revision: null
trust_remote_code: null
subfolder: ''
data_source_yaml_path: datasets/product_title_attribute_extraction/mave_title_genre.yaml
raw_cache_dir: /data/junwang/.cache/general
batch_size: 70
overwrite_cache: false
max_length: 50
predict_on_test: true
num_workers: 80
max_length_out: 50
