name: "product_classify_tokenizer"
max_batch_size: 64
backend: "python"

input [
    {
        name: "text"
        data_type: TYPE_STRING
        dims: [ 1 ]
    }
]

output [
    {
        name: "input_ids"
        data_type: TYPE_INT64
        dims: [ 512 ] 
    },
    {
        name: "attention_mask"
        data_type: TYPE_INT64
        dims: [ 512 ]
    }
]

dynamic_batching {
#   preferred_batch_size: [ 1,2,4,8,16,32,64 ]
#   max_queue_delay_microseconds: 5
}

instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]