model_name: google/mt5-base
weight_decay: 0.1
learning_rate: 1.0e-05
lr_scheduler_max_steps: null
lr_scheduler_type: null
lr_scheduler_num_warmup_steps: null
distance_func: cosine
loss_type: cross-entropy
margin: null
hidden_states_type: encoder-last
add_simcse: false
manual_loss_type: manual_mse
auto_task_weight: false
multitask_specs_dict:
  emb_singlemodal_wishquery2googletitle: null
head_dict: {}
return_model: true
cache_dir: null
force_download: false
resume_download: false
proxies: null
use_auth_token: null
local_files_only: false
revision: null
trust_remote_code: null
subfolder: ''
load_weights_only: true
multitask_dict:
  emb_singlemodal_wishquery2googletitle:
    data_source_yaml_path: datasets/multimodal_multitask/wish_query_all_googlescrape.yaml
    batch_size: 40
    max_length: 50
    max_length_out: 50
    llm_type: emb
    input_dict:
      template: '{title}'
      task_prefix: 'Embed product: '
    output_dict:
      template: '{query}'
      task_prefix: 'Embed query: '
    data_source_type: dvc
raw_cache_dir: /data/junwang/.cache/general
overwrite_cache: false
force_download_hfdata: false
predict_on_test: true
predict_on_trainval: null
num_workers: 8
multiple_trainloader_mode: min_size
