model_name: t5-base
weight_decay: 0.1
learning_rate: 1.0e-05
lr_scheduler_max_steps: null
lr_scheduler_type: null
lr_scheduler_num_warmup_steps: null
distance_func: cosine
loss_type: cross-entropy
margin: null
hidden_states_type: encoder-last
add_simcse: false
manual_loss_type: manual_mse
auto_task_weight: false
multitask_specs_dict:
  clm_multimodal_clip2wishtitle:
    multimodal_embedding:
      input:
      - key: img_embedding
        proj_head: proj_head
  dlm_multimodal_wishtitlewclip2wishtitle:
    multimodal_embedding:
      input:
      - key: img_embedding
        proj_head: proj_head
  seqclf_multimodal_wishtitlewclip2pseudov121tax:
    multimodal_embedding:
      input:
      - key: img_embedding
        proj_head: proj_head
    specs:
      clf_head: clf_head
      clf_weight_type: null
      label_map_file: datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
      label_type: taxonomy
  emb_singlemodal_wishquery2googletitle: null
  clm_singlemodal_alititle2v121tax: null
  clm_singlemodal_wishtitle2pseudov121tax: null
  dlm_singlemodal_wishtitle: null
  emb_singlemodal_wishtitle2pseudov121tax: null
  emb_singlemodal_alititle2v121tax: null
  seqclf_singlemodal_alititle2v121tax:
    specs:
      clf_head: clf_head
      clf_weight_type: null
      label_map_file: datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
      label_type: taxonomy
  seqclf_singlemodal_wishtitle2pseudov121tax:
    specs:
      clf_head: clf_head
      clf_weight_type: null
      label_map_file: datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
      label_type: taxonomy
head_dict:
  proj_head:
    type: linear
    in_features: 768
    out_features: 768
    purpose: projection
  clf_head:
    type: linear
    in_features: 768
    out_features: 6037
    purpose: seqclf
return_model: true
cache_dir: null
force_download: false
resume_download: false
proxies: null
use_auth_token: null
local_files_only: false
revision: null
trust_remote_code: null
subfolder: ''
load_weights_only: true
multitask_dict:
  clm_multimodal_clip2wishtitle:
    data_source_yaml_path: datasets/multimodal_multitask/wish_tahoe_clipmore.yaml
    batch_size: 2
    max_length: 50
    max_length_out: 50
    llm_type: clm
    input_dict:
      template: '[image start] {img_embedding} [image end]'
      task_prefix: 'Generate title for product with image: '
      is_multimodal_embedding:
      - img_embedding
    output_dict:
      template: '{title}'
    data_source_type: dvc
  dlm_multimodal_wishtitlewclip2wishtitle:
    data_source_yaml_path: datasets/multimodal_multitask/wish_tahoe_clipmore.yaml
    batch_size: 2
    max_length: 50
    max_length_out: 50
    use_ul2: true
    llm_type: dlm
    input_dict:
      template: '[title start] {title} [title end] [image start] {img_embedding} [image
        end]'
      task_prefix: 'Denoise product with image: '
      is_multimodal_embedding:
      - img_embedding
    output_dict:
      template: '{title}'
    data_source_type: dvc
  seqclf_multimodal_wishtitlewclip2pseudov121tax:
    data_source_yaml_path: datasets/multimodal_multitask/wish_tahoe_clipmore_joined_pseudolabel_train_resplit.yaml
    batch_size: 2
    max_length: 50
    max_length_out: 50
    label_map_file: datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
    label_type: taxonomy
    llm_type: seqclf
    input_dict:
      template: '[title start] {title} [title end] [image start] {img_embedding} [image
        end]'
      task_prefix: 'Classify product with image: '
      is_multimodal_embedding:
      - img_embedding
    output_dict:
      template: '{v121_category_multitaskv0_1_pseudo}'
    transform_dict:
      v121_category_multitaskv0_1_pseudo: taxonomy
    data_source_type: dvc
  emb_singlemodal_wishquery2googletitle:
    data_source_yaml_path: datasets/multimodal_multitask/wish_query_100k_googlescrape.yaml
    batch_size: 80
    max_length: 50
    max_length_out: 50
    llm_type: emb
    input_dict:
      template: '{title}'
      task_prefix: 'Embed product: '
    output_dict:
      template: '{query}'
      task_prefix: 'Embed query: '
    data_source_type: dvc
  clm_singlemodal_alititle2v121tax:
    data_source_yaml_path: datasets/multimodal_multitask/ali_title_to_121tax.yaml
    batch_size: 2
    max_length: 50
    max_length_out: 50
    llm_type: clm
    input_dict:
      template: '{title}'
      task_prefix: 'Generate taxonomy for product: '
    output_dict:
      template: '{category}'
    transform_dict:
      category: taxonomy
    data_source_type: dvc
  clm_singlemodal_wishtitle2pseudov121tax:
    data_source_yaml_path: datasets/multimodal_multitask/wish_pseudo_clean.yaml
    batch_size: 2
    max_length: 50
    max_length_out: 50
    llm_type: clm
    input_dict:
      template: '{title}'
      task_prefix: 'Generate taxonomy for product: '
    output_dict:
      template: '{multitask_seqclf_v0_1_predicted_category}'
    transform_dict:
      multitask_seqclf_v0_1_predicted_category: taxonomy
    data_source_type: local
  dlm_singlemodal_wishtitle:
    data_source_yaml_path: datasets/multimodal_multitask/wish_tahoe.yaml
    batch_size: 2
    max_length: 50
    max_length_out: 50
    use_ul2: true
    llm_type: dlm
    input_dict:
      template: '{title}'
      task_prefix: 'Denoise product: '
    output_dict:
      template: '{title}'
    data_source_type: dvc
  emb_singlemodal_wishtitle2pseudov121tax:
    data_source_yaml_path: datasets/multimodal_multitask/wish_pseudo_clean.yaml
    batch_size: 10
    max_length: 50
    max_length_out: 50
    llm_type: emb
    input_dict:
      template: '{title}'
      task_prefix: 'Embed product: '
    output_dict:
      template: '{multitask_seqclf_v0_1_predicted_category}'
      task_prefix: 'Embed taxonomy: '
    transform_dict:
      multitask_seqclf_v0_1_predicted_category: taxonomy
    data_source_type: local
  emb_singlemodal_alititle2v121tax:
    data_source_yaml_path: datasets/multimodal_multitask/ali_title_to_121tax.yaml
    batch_size: 10
    max_length: 50
    max_length_out: 50
    llm_type: emb
    input_dict:
      template: '{title}'
      task_prefix: 'Embed product: '
    output_dict:
      template: '{category}'
      task_prefix: 'Embed taxonomy: '
    transform_dict:
      category: taxonomy
    data_source_type: dvc
  seqclf_singlemodal_alititle2v121tax:
    data_source_yaml_path: datasets/multimodal_multitask/ali_title_to_121tax.yaml
    batch_size: 2
    max_length: 50
    max_length_out: 50
    label_map_file: datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
    label_type: taxonomy
    llm_type: seqclf
    input_dict:
      template: '{title}'
      task_prefix: 'Classify product: '
    output_dict:
      template: '{category}'
    transform_dict:
      category: taxonomy
    data_source_type: dvc
  seqclf_singlemodal_wishtitle2pseudov121tax:
    data_source_yaml_path: datasets/multimodal_multitask/wish_pseudo_clean.yaml
    batch_size: 2
    max_length: 50
    max_length_out: 50
    label_map_file: datasets/taxonomy/wish_v1.2.1_newtax_allpaths.txt
    label_type: taxonomy
    llm_type: seqclf
    input_dict:
      template: '{title}'
      task_prefix: 'Classify product: '
    output_dict:
      template: '{multitask_seqclf_v0_1_predicted_category}'
    transform_dict:
      multitask_seqclf_v0_1_predicted_category: taxonomy
    data_source_type: local
raw_cache_dir: /data/junwang/.cache/general
overwrite_cache: false
force_download_hfdata: false
predict_on_test: true
num_workers: 0
multiple_trainloader_mode: max_size_cycle
