name: "query_classify_postprocess"
max_batch_size: 64
backend: "python"

input [
    {
        name: "logits"
        data_type: TYPE_FP32
        dims: [ 6038 ]
    }
]

output [
    {
        name: "categories"
        data_type: TYPE_STRING
        dims: [ 1 ] 
    },
    {
        name: "weights"
        data_type: TYPE_STRING
        dims: [ 1 ] 
    }
]
dynamic_batching {
  preferred_batch_size: [ 1,2,4,8,16,32,64 ]
  max_queue_delay_microseconds: 5
}
instance_group [
    {
      count: 1
      kind: KIND_CPU
    }
]